In [3]:
import numpy as np
import pandas as pd
a=pd.Series([10,20,30,40,np.nan,50,np.nan,32],index=["a","b","c","d","e","f","g","h"])
print("Serires 1")
print(a)

Serires 1
a    10.0
b    20.0
c    30.0
d    40.0
e     NaN
f    50.0
g     NaN
h    32.0
dtype: float64


In [4]:
#to find the empty value
a.isna()

a    False
b    False
c    False
d    False
e     True
f    False
g     True
h    False
dtype: bool

In [6]:
#to find the no of null values or empty values 
print("The Number of Null and Empty Value is =",a.isna().sum())

The Number of Null and Empty Value is = 2


In [7]:
b=pd.Series([np.nan,11,np.nan,22,np.nan,33],index=["a","b","c","d","e","f"])
print(b)

a     NaN
b    11.0
c     NaN
d    22.0
e     NaN
f    33.0
dtype: float64


In [8]:
print(a.isna())

a    False
b    False
c    False
d    False
e     True
f    False
g     True
h    False
dtype: bool


In [11]:
for val in b.isna():
    print(val)

True
False
True
False
True
False


In [14]:
print(b.isna())

a     True
b    False
c     True
d    False
e     True
f    False
dtype: bool


In [15]:
print("The No of empty Value= ",b.isna().sum())

The No of empty Value=  3


In [16]:
print(b.isnull())

a     True
b    False
c     True
d    False
e     True
f    False
dtype: bool


In [18]:
print("Total Null values=",b.isnull().sum())

Total Null values= 3


In [19]:
print("Total Null Values in a =",a.isnull().sum())

Total Null Values in a = 2


In [20]:
print(b.isnull())

a     True
b    False
c     True
d    False
e     True
f    False
dtype: bool


In [21]:
c=pd.Series([10,33,24,55,22,34,91,0,3],index=["a","b","c","d","e","f","g","h","i"])
print(c)

a    10
b    33
c    24
d    55
e    22
f    34
g    91
h     0
i     3
dtype: int64


In [ ]:
#Sorting the Values of Series
#Syntax:   seriesobj.sort_values(ascending,inplace)
#seriesobj.sort_values()
#seriesobj.sort_values(inplace)
#seriesobj.sort_values(ascending)

In [24]:
print(c.sort_values())

h     0
i     3
a    10
e    22
c    24
b    33
f    34
d    55
g    91
dtype: int64


In [33]:
print(c.sort_values(ascending=False,inplace=True))

None


In [34]:
print(c.sort_values(ascending=True))

h     0
i     3
a    10
e    22
c    24
b    33
f    34
d    55
g    91
dtype: int64


In [35]:
print(c.sort_values(ascending=False))

g    91
d    55
f    34
b    33
c    24
e    22
a    10
i     3
h     0
dtype: int64


In [36]:
print(c.sort_values(inplace=False))

h     0
i     3
a    10
e    22
c    24
b    33
f    34
d    55
g    91
dtype: int64


In [37]:
print(c.sort_values(ascending=True,inplace=False))

h     0
i     3
a    10
e    22
c    24
b    33
f    34
d    55
g    91
dtype: int64


In [38]:
#to print the ascending values using for loop
for val in c.sort_values():
    print(val)

0
3
10
22
24
33
34
55
91


In [39]:
#To Print the Descending Value using for loop
for val in c.sort_values(ascending=False):
    print(val)


91
55
34
33
24
22
10
3
0


In [ ]:
#Finding Max / Highest Element from Series and Number Approaches
#SeriesObj.max()
#SeriesObj.nlargest(n)

In [42]:
c=pd.Series([10,20,30,40,50,3,66,99,32,45,94])
print("Series is =\n",c)

Series is =
 0     10
1     20
2     30
3     40
4     50
5      3
6     66
7     99
8     32
9     45
10    94
dtype: int64


In [43]:
#to find the max no of element form series
print(c.max())

99


In [44]:
print("Max no is =",c.max())

Max no is = 99


In [46]:
#using the nlargest(n)
print(c.nlargest())

7     99
10    94
6     66
4     50
9     45
dtype: int64


In [47]:
print(c.nlargest(1))

7    99
dtype: int64


In [48]:
#to get no of largest element
print(c.nlargest(3))

7     99
10    94
6     66
dtype: int64


In [55]:
#to get the sum of first 2 largest no
print(c.nlargest(2).sum())

193


In [ ]:
#Finding Min / smallest Element from Series and Number Approaches
#SeriesObj.min()
#SeriesObj.nsmallest(n)

In [56]:
c=pd.Series([10,20,30,40,50,3,66,99,32,45,94])
print("Series is =\n",c)

Series is =
 0     10
1     20
2     30
3     40
4     50
5      3
6     66
7     99
8     32
9     45
10    94
dtype: int64


In [57]:
#to find the minimum no of element from the series
print(c.min())

3


In [58]:
print("The Minimum no of Series is =",c.min())

The Minimum no of Series is = 3


In [62]:
#to print the smallest no using nsmallest(n)
print("Smallest No =\n",c.nsmallest())

Smallest No =
 5     3
0    10
1    20
2    30
8    32
dtype: int64


In [63]:
#to print the 1st three smallest no
print(c.nsmallest(3))

5     3
0    10
1    20
dtype: int64


In [65]:
#to print the sum of 1sst three smallest no 
print(c.nsmallest(3).sum())

33


In [ ]:
#Finding Unique Values from Series 
#Syntax:    serobj.unique()

In [66]:
c.unique()

array([10, 20, 30, 40, 50,  3, 66, 99, 32, 45, 94])

In [67]:
a=pd.Series([1,2,3,4,1,2,5,6,7,33,22,1,2,3,4])
print(a)

0      1
1      2
2      3
3      4
4      1
5      2
6      5
7      6
8      7
9     33
10    22
11     1
12     2
13     3
14     4
dtype: int64


In [68]:
print(c.unique())

[10 20 30 40 50  3 66 99 32 45 94]


In [69]:
print(c.unique().sum())

489


In [70]:
print(c.unique())

[10 20 30 40 50  3 66 99 32 45 94]


In [ ]:
#Finding Number of Unique Values from Series 
# serobj.nunique()

In [71]:
#to find the no of unique values from the series 
print(c.nunique())

11


In [72]:
print("No of unuque values =",c.nunique())

No of unuque values = 11


In [ ]:
#Display Unique Values from Series Object.
#Syntax:   serobj.value_counts()

In [73]:
c.value_counts()

10    1
20    1
30    1
40    1
50    1
3     1
66    1
99    1
32    1
45    1
94    1
Name: count, dtype: int64

In [75]:
print(c.value_counts())

10    1
20    1
30    1
40    1
50    1
3     1
66    1
99    1
32    1
45    1
94    1
Name: count, dtype: int64


In [77]:
a=pd.Series([1,2,3,4,1,2,3,2,2,1,2,])
print(a)

0     1
1     2
2     3
3     4
4     1
5     2
6     3
7     2
8     2
9     1
10    2
dtype: int64


In [79]:
#to count the no of values repeating time
a.value_counts()

2    5
1    3
3    2
4    1
Name: count, dtype: int64