In [4]:
import numpy as np
a=np.array([10,20,30,40,50,60,70,80,90,15,25,35])
print("-------------------------------------------------")
print("Content of a")
print(a)
print("Dimension of a=",a.ndim)
print("Shape of a=",a.shape)
print("Size of a=",a.size)
print("-------------------------------------------------")

-------------------------------------------------
Content of a
[10 20 30 40 50 60 70 80 90 15 25 35]
Dimension of a= 1
Shape of a= (12,)
Size of a= 12
-------------------------------------------------


In [5]:
#to get the index value of 10,40,50
lst=[0,3,4]
a[lst]

array([10, 40, 50])

In [6]:
a[[0,3,4]]

array([10, 40, 50])

In [8]:
a[[0,3,4]]

array([10, 40, 50])

In [11]:
import numpy as np
from numpy import random as r
lst=r.randint(0,25,size=10)
print(lst)

[17  9 11 23 14 21 23 23 14 24]


In [13]:
for value, index in enumerate(lst):
    print(value,"--->",index)

0 ---> 17
1 ---> 9
2 ---> 11
3 ---> 23
4 ---> 14
5 ---> 21
6 ---> 23
7 ---> 23
8 ---> 14
9 ---> 24


In [15]:
lst[[2,5]]

array([11, 21], dtype=int32)

In [16]:
b=[0,3,9]
lst[b]

array([17, 23, 24], dtype=int32)

In [17]:
rv=r.randint(1,100,size=(5,5))
print(rv)

[[68 39 47  7 89]
 [36 77 66 51 41]
 [46 56 20 82 16]
 [66 42 90 14 45]
 [12 52 59 91 68]]


In [18]:
print("size of array=",a.size)
print("shape of array =",a.shape)
print("Dim of array=",a.ndim)

size of array= 12
shape of array = (12,)
Dim of array= 1


In [ ]:
#Steps for Advanced Indexing with 2-D
#Step-1: Identify the Row Indices of Elements and places them in Traditional Python Object/ndarray object
#Step-2: Identify the Column Indices of Elements and places them in Traditional Python Object/ndarray object
#Step-3: Pass Row Indices and Column Indices to ndarray Object