In [9]:
import numpy as np
from numpy import random as r
a=r.randint(0,100,size=(16)).reshape(4,4)
print(a)

[[76 54 90 36]
 [97 60 51 26]
 [70 41  3 22]
 [66 12 15 71]]


In [11]:
#to get the value of all ends
a[::3,::3]

array([[76, 36],
       [66, 71]], dtype=int32)

In [13]:
#to get the values of last two col
a[::,2:4]

array([[90, 36],
       [51, 26],
       [ 3, 22],
       [15, 71]], dtype=int32)

In [15]:
#To get the value of 51,26
a[1:2,2:4]

array([[51, 26]], dtype=int32)

In [17]:
#To Get the Value of 41,3
a[2:3,1:3]

array([[41,  3]], dtype=int32)

In [19]:
a[-1:,-4:-3]

array([[66]], dtype=int32)

In [21]:
a[0:,0:2]

array([[76, 54],
       [97, 60],
       [70, 41],
       [66, 12]], dtype=int32)

In [22]:
a[2:,0::]

array([[70, 41,  3, 22],
       [66, 12, 15, 71]], dtype=int32)

In [ ]:
# N-D Array Slicing
#Syntax:NDarrayobj[MatRowBeg:MatRowEnd:MatStep,RowBegin:RowEnd:RowStep, ColBegin:ColEnd:ColStep]  

In [23]:
a=np.array([10,20,30,40,50,60,70,80,90,15,25,35,55,65,75,12]).reshape(2,4,2)
print("Content of a")
print(a)

Content of a
[[[10 20]
  [30 40]
  [50 60]
  [70 80]]

 [[90 15]
  [25 35]
  [55 65]
  [75 12]]]


In [24]:
a[0:1:2,0::,::3]

array([[[10],
        [30],
        [50],
        [70]]])

In [27]:
a[0:1,0:1,0:2]

array([[[10, 20]]])

In [28]:
a[0:1,3:,0:1]

array([[[70]]])

In [29]:
a[0:1,2:3,1:]

array([[[60]]])

In [30]:
a[0:2,0:1,0:2]

array([[[10, 20]],

       [[90, 15]]])

In [31]:
a[0:2,0:2,0:2]

array([[[10, 20],
        [30, 40]],

       [[90, 15],
        [25, 35]]])