In [3]:
#Array 

import numpy as np
lst=[10,20,30,40,50,60]
print("Origrinal List =",lst)
lst1=np.array(lst)
print("After Converted List =",lst1)
print("----------------------")
print("shape of Array=",lst1.shape)
print("Size of Array =",lst1.size)
print("Dim of Array =",lst1.ndim)
print("Reshape of Array =")
print(lst1.reshape(3,2))

Origrinal List = [10, 20, 30, 40, 50, 60]
After Converted List = [10 20 30 40 50 60]
----------------------
shape of Array= (6,)
Size of Array = 6
Dim of Array = 1
Reshape of Array =
[[10 20]
 [30 40]
 [50 60]]


In [10]:
#arange

#varname=numpy.aragne(value)

import numpy as np
a=np.arange(10)
print(a)
print("----------------------")
print("shape of Array=",a.shape)
print("Size of Array =",a.size)
print("Dim of Array =",a.ndim)


[0 1 2 3 4 5 6 7 8 9]
----------------------
shape of Array= (10,)
Size of Array = 10
Dim of Array = 1


In [11]:
#varname=numpy.arange(start,stop)
b=np.arange(1,13)
print(b)
print("----------------------")
print("shape of Array=",b.shape)
print("Size of Array =",b.size)
print("Dim of Array =",b.ndim)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
----------------------
shape of Array= (12,)
Size of Array = 12
Dim of Array = 1


In [12]:
#varname=numpy.arange(start,stop,step)
c=np.arange(1,10,2)
print(c)
print("----------------------")
print("shape of Array=",c.shape)
print("Size of Array =",c.size)
print("Dim of Array =",c.ndim)

[1 3 5 7 9]
----------------------
shape of Array= (5,)
Size of Array = 5
Dim of Array = 1


In [15]:
#zeros
#varname=numpy.zeros(shape,dtype)

a=np.zeros(2)
print(a)
print("----------------------")
print("shape of Array=",a.shape)
print("Size of Array =",a.size)
print("Dim of Array =",a.ndim)

[0. 0.]
----------------------
shape of Array= (2,)
Size of Array = 2
Dim of Array = 1


In [16]:
#varname=numpy.zeros(shape,dtype)

a=np.zeros(3,dtype=int)
print(a)
print("----------------------")
print("shape of Array=",a.shape)
print("Size of Array =",a.size)
print("Dim of Array =",a.ndim)

[0 0 0]
----------------------
shape of Array= (3,)
Size of Array = 3
Dim of Array = 1


In [17]:
#ONES

#varname=numpy.ones(shape)
a=np.ones(3)
print(a)
print("----------------------")
print("shape of Array=",a.shape)
print("Size of Array =",a.size)
print("Dim of Array =",a.ndim)

[1. 1. 1.]
----------------------
shape of Array= (3,)
Size of Array = 3
Dim of Array = 1


In [18]:
#varname=numpy.ones(shape,dtype)
a=np.ones(5,dtype=int)
print(a)
print("----------------------")
print("shape of Array=",a.shape)
print("Size of Array =",a.size)
print("Dim of Array =",a.ndim)


[1 1 1 1 1]
----------------------
shape of Array= (5,)
Size of Array = 5
Dim of Array = 1


In [22]:
#full
#varname=numpy.full(shape,fill_value=value,dtype)
a=np.full(4,fill_value=3)
print(a)
print("----------------------")
print("shape of Array=",a.shape)
print("Size of Array =",a.size)
print("Dim of Array =",a.ndim)

[3 3 3 3]
----------------------
shape of Array= (4,)
Size of Array = 4
Dim of Array = 1


In [23]:
b=np.full(6,fill_value=2)
print(b)
print("----------------------")
print("shape of Array=",b.shape)
print("Size of Array =",b.size)
print("Dim of Array =",b.ndim)

[2 2 2 2 2 2]
----------------------
shape of Array= (6,)
Size of Array = 6
Dim of Array = 1


In [25]:
#linspace
#varname=numpy.linspace(start,stop,num,endpoint,restep,dtype)

a=np.linspace(4,9,4)
print(a)

[4.         5.66666667 7.33333333 9.        ]


In [26]:
b=np.linspace(2,6,10)
print(b)

[2.         2.44444444 2.88888889 3.33333333 3.77777778 4.22222222
 4.66666667 5.11111111 5.55555556 6.        ]


In [27]:
#identity
#varname=numpy.identity(n,dtype)
a=np.identity(3)
print(a)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [28]:
b=np.identity(4,dtype=int)
print(b)

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]


In [29]:
a=np.identity(5,dtype=int)
print(a)

[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]


In [30]:
#eye()

#varname=numpy.eye(N,M=none,k=0,dtype)

a=np.eye(3)
print(a)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [31]:
a=np.eye(2,3)
print(a)

[[1. 0. 0.]
 [0. 1. 0.]]


In [32]:
b=np.eye(3,2)
print(b)

[[1. 0.]
 [0. 1.]
 [0. 0.]]


In [33]:
b=np.eye(3,2,k=3)
print(b)

[[0. 0.]
 [0. 0.]
 [0. 0.]]


In [34]:
a=np.eye(3,3,k=2)
print(a)

[[0. 0. 1.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [35]:
a=np.eye(5,5,k=2)
print(a)

[[0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [36]:
a=np.eye(5,5,k=3)
print(a)
print("----------------------------")
print("Shape of Array=",a.shape)
print("Size of Array=",a.size)
print("Dim of Array =",a.ndim)

[[0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
----------------------------
Shape of Array= (5, 5)
Size of Array= 25
Dim of Array = 2


In [39]:
#hstack

#varname=numpy.hstack((ndarrayobj1,ndarrayobj2))

a=np.array([[10,20,30,40],[50,60,70,80]])
print("array1")
print(a)
b=np.array([[1,2,3,4],[3,4,4,5]])
print(b)

array1
[[10 20 30 40]
 [50 60 70 80]]
[[1 2 3 4]
 [3 4 4 5]]


In [41]:
c=np.hstack((a,b))
print("Merged Array")
print(c)

Merged Array
[[10 20 30 40  1  2  3  4]
 [50 60 70 80  3  4  4  5]]


In [42]:
c=np.vstack((a,b))
print("Merged Array")
print(c)

Merged Array
[[10 20 30 40]
 [50 60 70 80]
 [ 1  2  3  4]
 [ 3  4  4  5]]


In [45]:
c=np.hstack((a,b))
d=c.reshape(3,2)
print(d)

ValueError: cannot reshape array of size 16 into shape (3,2)