In [1]:
import numpy as np
from numpy import random as r
a=np.array([10,20,30,40,50,60])
print(a,type(a))

[10 20 30 40 50 60] <class 'numpy.ndarray'>


In [3]:
b=a.reshape(3,2)
print(b)

[[10 20]
 [30 40]
 [50 60]]


In [6]:
#shallow copy is = copy
c=a.copy()
print(a,type(a),id(a))
print("-----------------------")
print(c,type(c),id(c))

[10 20 30 40 50 60] <class 'numpy.ndarray'> 1966616598384
-----------------------
[10 20 30 40 50 60] <class 'numpy.ndarray'> 1967063850064


In [8]:
#deep copy is = view
c=a
print(a,id(a))
print(c,id(c))

[10 20 30 40 50 60] 1966616598384
[10 20 30 40 50 60] 1966616598384


In [10]:
a[0]=100
print(a)
print("The id of a is =",id(a))

[100  20  30  40  50  60]
The id of a is = 1966616598384


In [12]:
print(c)
print("The id of c=",id(c))

[100  20  30  40  50  60]
The id of c= 1966616598384


In [13]:
#view
arr=np.array([10,20,30,40,50,60,70,80])
arr2=arr.view()
print(arr2,id(arr2),type(arr2))

[10 20 30 40 50 60 70 80] 1967065845552 <class 'numpy.ndarray'>


In [14]:
print(arr,id(arr),type(arr))

[10 20 30 40 50 60 70 80] 1967063850736 <class 'numpy.ndarray'>


In [15]:
print("The Base of arr=",arr.base)
print("The Base of arr2=",arr2.base)

The Base of arr= None
The Base of arr2= [10 20 30 40 50 60 70 80]


In [17]:
a=np.array([10,20,30,40,50])
print("Array =",a,id(a))

Array = [10 20 30 40 50] 1967070316560


In [18]:
b=a.copy()
print("Array=",b,id(b))

Array= [10 20 30 40 50] 1967070317808


In [19]:
print("Base of a=",a.base)
print("Base of b=",b.base)

Base of a= None
Base of b= None


In [23]:
b=a
print("Base of a=",a.base)
print("Base of b=",b.base)

Base of a= None
Base of b= None
