In [2]:
import numpy as np
from numpy import random
a=np.array([10,15,25,30,35,40,45,34,56,67,19,18])
print("Content of a")
print(a)

Content of a
[10 15 25 30 35 40 45 34 56 67 19 18]


In [26]:
#To get the Even No from the array
nb=a%2==0
print(nb)

[ True  True  True False  True False False  True False  True  True False
  True  True]


In [27]:
a[nb]

array([ 10,  12,  34,   6,  -2,  -6,   6, -44, -22])

In [28]:
#To Get The Odd No From The array
nb=a%2!=0
print(nb)

[False False False  True False  True  True False  True False False  True
 False False]


In [29]:
a[nb]

array([55,  3, -1, 45, -7])

In [23]:
a=np.array([10,12,34,55,6,3,-1,-2,45,-6,6,-7,-44,-22])
print(a)

[ 10  12  34  55   6   3  -1  -2  45  -6   6  -7 -44 -22]


In [24]:
#To Get a Positive Value From a array
pv=(a>0)
print(pv)

[ True  True  True  True  True  True False False  True False  True False
 False False]


In [30]:
a[pv]

array([10, 12, 34, 55,  6,  3, 45,  6])

In [31]:
#To Get The Negative Value From The Array
nv=(a<0)
print(nv)

[False False False False False False  True  True False  True False  True
  True  True]


In [32]:
a[nv]

array([ -1,  -2,  -6,  -7, -44, -22])

In [5]:
#to print the mul value of 3 and 5
import numpy as np
from numpy import random as r
a=r.randint(1,100,size=(14))
print(a)
vl=(a%3==0)&(a%5==0)
a[vl]


[47 43 42  7 77 13 57 90 88 85 57 79 36 30]


array([90, 30], dtype=int32)

In [6]:
import numpy as np
from numpy import random as r

In [15]:
a=r.randint(1,50,size=20)
print("The Array is =",a)
print("Size of Array =",a.size)
print("Dim of Array =",a.ndim)
print("Shape of Array=",a.shape)

The Array is = [11 18 38 35 15 36 48 12 42 18 13 20 16 31 31 25 41  5 13 35]
Size of Array = 20
Dim of Array = 1
Shape of Array= (20,)


In [18]:
#get multiple 3 using the numpy.where()
a=r.randint(1,50,size=20)
ind=np.where(a%3==0)
print(ind)
for i in ind[0]:
    print(i)

(array([ 3,  5, 10, 12, 15, 18]),)
3
5
10
12
15
18


In [20]:
#to get the +ve elements by using numpy.where()
ind=np.where(a>0)
print(ind)
for i in ind[0]:
    print(a[i])

(array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19]),)
1
2
46
6
14
48
22
4
35
49
3
16
42
14
47
9
23
11
39
13


In [5]:
#working with missing data
import numpy as np
data=np.array([1,2,None,3,4])
print(data)

[1 2 None 3 4]


In [3]:
#Replace misssing with 0
data=np.where(data==None,0,data)
print(data)

[1 2 0 3 4]


In [6]:
#filter missing values
data=np.extract(data!=None,data)
print(data)

[1 2 3 4]


In [12]:
#Example on numpy.extract(TestCond,ndarrayobj)
import numpy as np
from numpy import random
a=np.random.randint(2,40,size=14)
print(a)
#get the value whiech are more than 20
print("-----------------------")
morethan20=np.extract(a>20,a)
print("Greater Than 20=",morethan20)

[35 18  2 29 18 39  9 13 24 35  5 12  9 10]
-----------------------
Greater Than 20= [35 29 39 24 35]


In [16]:
#Searching the array
arr=np.array([10,20,30,40,50,60])
x=np.where(arr==20)
print(x)

(array([1]),)


In [17]:
y=np.where(arr%2==0)
print(y)

(array([0, 1, 2, 3, 4, 5]),)
