In [11]:
import numpy as np
from numpy import random as r
a=np.array([10,20,30,40,50,60,70,80,90,12,55,66]).reshape(2,3,2)
print(a)

[[[10 20]
  [30 40]
  [50 60]]

 [[70 80]
  [90 12]
  [55 66]]]


In [13]:
#converting 3darray to 1darray
c=a.flatten()
print(c)

[10 20 30 40 50 60 70 80 90 12 55 66]


In [16]:
a=np.array([10,20,30,40,50,60,70,80,90,12,55,66]).reshape(2,3,2)
print(a)
d=a.ravel()
print(d)

[[[10 20]
  [30 40]
  [50 60]]

 [[70 80]
  [90 12]
  [55 66]]]
[10 20 30 40 50 60 70 80 90 12 55 66]


In [17]:
#converting 2d array to 1d array
a=np.array([10,20,30,40,50,60]).reshape(3,2)
print(a)

[[10 20]
 [30 40]
 [50 60]]


In [18]:
b=a.flatten()
print("Flatten Array =",b)

Flatten Array = [10 20 30 40 50 60]


In [19]:
#to convert the 2d,3rd, nd array to 1d array we use the flatten and ravel.