In [2]:
import numpy as np
a=np.array([10,20,30,40,50,60,70,80])
print(a,type(a))
print("Shape of Array=",a.shape)
print("Dim of Array=",a.ndim)
print("Size of Array=",a.size)

[10 20 30 40 50 60 70 80] <class 'numpy.ndarray'>
Shape of Array= (8,)
Dim of Array= 1
Size of Array= 8


In [5]:
#to get the value 10
print(a[0])

10


In [6]:
#to get the value of 70
print(a[-2])

70


In [7]:
#to get the value of 50
print(a[4])

50


In [9]:
a=np.array([10,20,30,40,50,60,]).reshape(3,2)
print(a)
print("Shape of Array=",a.shape)
print("Dim of Array=",a.ndim)
print("Size of Array=",a.size)

[[10 20]
 [30 40]
 [50 60]]
Shape of Array= (3, 2)
Dim of Array= 2
Size of Array= 6


In [10]:
print(a[0,1])

20


In [11]:
print(a[0][1])

20


In [12]:
print(a[1,1])

40


In [16]:
print(a[1,1])

40


In [17]:
#to get the all row value 
a[0]

array([10, 20])

In [18]:
a[2]

array([50, 60])

In [20]:
a[1,1]

np.int64(40)

In [21]:
a=np.array([10,20,30,40,50,60,70,80,90,15,25,35]).reshape(2,3,2)
print("-------------------------------------------------")
print("Content of a")
print(a)
print("Dimension of a=",a.ndim)
print("Shape of a=",a.shape)
print("Size of a=",a.size)
print("-------------------------------------------------")

-------------------------------------------------
Content of a
[[[10 20]
  [30 40]
  [50 60]]

 [[70 80]
  [90 15]
  [25 35]]]
Dimension of a= 3
Shape of a= (2, 3, 2)
Size of a= 12
-------------------------------------------------


In [22]:
a[0,1,1]

np.int64(40)

In [23]:
#to get the 70 value from 2nd matrix
a[1,0,0]

np.int64(70)

In [24]:
#to get the 35 value from 2nd matrix
a[1,2,1]

np.int64(35)

In [25]:
a[0,2,1]

np.int64(60)