In [1]:
#Iterating Array Without Fun
import numpy as np
from numpy import random

In [2]:
arr=np.array([10,20,30,40,50,60])
for x in arr:
    print(x)

10
20
30
40
50
60


In [8]:
arr2=np.array([[1,2,3,4,5],[10,20,30,40,50]])
for x in arr2:
    print(arr2)

[[ 1  2  3  4  5]
 [10 20 30 40 50]]
[[ 1  2  3  4  5]
 [10 20 30 40 50]]


In [9]:
for x in arr2:
    for y in x:
        print(y)

1
2
3
4
5
10
20
30
40
50


In [22]:
arr=np.array([[[1,2,3],[4,5,6]],[[12,13,14],[16,17,18]]])
for x in arr:
    print(x)

[[1 2 3]
 [4 5 6]]
[[12 13 14]
 [16 17 18]]


In [24]:
for x in np.nditer(arr):
    print(x)

1
2
3
4
5
6
12
13
14
16
17
18


In [25]:
for idx,x in np.ndenumerate(arr):
    print(idx,"--->",x)

(0, 0, 0) ---> 1
(0, 0, 1) ---> 2
(0, 0, 2) ---> 3
(0, 1, 0) ---> 4
(0, 1, 1) ---> 5
(0, 1, 2) ---> 6
(1, 0, 0) ---> 12
(1, 0, 1) ---> 13
(1, 0, 2) ---> 14
(1, 1, 0) ---> 16
(1, 1, 1) ---> 17
(1, 1, 2) ---> 18


In [31]:
import numpy as np
from numpy import random as r
arr2=r.randint(1,12,size=12)
print(arr2)

[ 8  6 10  6 11  4 11  4  4 11  2  7]


In [32]:
for x in np.nditer(arr2):
    print(x)

8
6
10
6
11
4
11
4
4
11
2
7


In [33]:
for x in np.ndenumerate(arr2):
    print(x)

((0,), np.int32(8))
((1,), np.int32(6))
((2,), np.int32(10))
((3,), np.int32(6))
((4,), np.int32(11))
((5,), np.int32(4))
((6,), np.int32(11))
((7,), np.int32(4))
((8,), np.int32(4))
((9,), np.int32(11))
((10,), np.int32(2))
((11,), np.int32(7))
