In [1]:
import numpy as np
#create a numpy array of integers
arr=np.array([10,2,3,5,66,3])
#add/append an element at the end of numpy array 
new_arr=np.append(arr,22)
print("Original Array",arr)
print("New Array=",new_arr)

Original Array [10  2  3  5 66  3]
New Array= [10  2  3  5 66  3 22]


In [2]:
#adding the 54 element at the end 
new_arr=np.append(arr,54)

In [3]:
print(new_arr)

[10  2  3  5 66  3 54]


In [4]:
#adding the 33 element to the arr
new_arr=np.append(arr,33)

In [5]:
print(new_arr)

[10  2  3  5 66  3 33]


In [7]:
#Insert 
a=np.array([10,20,30,40,50])
print("Original Array=",a)
#inerting the element to the array a
a=np.insert(a,1,33)
print("Updated Array=",a)

Original Array= [10 20 30 40 50]
Updated Array= [10 33 20 30 40 50]


In [8]:
a=np.insert(a,-1,55)

In [9]:
print(a)

[10 33 20 30 40 55 50]


In [11]:
a=np.insert(a,-3,23)

In [12]:
print(a)

[10 33 20 30 23 23 40 55 50]


In [15]:
#delete the value at index postion 1
a=np.delete(a,1)
print(a)

[10 30 23 23 40 55 50]


In [17]:
a=np.delete(a,-1)
print(a)

[10 30 23 23 40 55]


In [18]:
#deleting the element at index position -2
a=np.delete(a,-2)
print(a)

[10 30 23 23 55]


In [ ]:
#If 1 then then delete columns
#if 0 the delete rows

In [22]:
#deleting the rows & columns from the 2D numpy Array
arr=np.array([[11,22,11,22],
             [22,33,23,23],
             [43,43,54,21],
             [66,45,67,23]])
print(arr)

[[11 22 11 22]
 [22 33 23 23]
 [43 43 54 21]
 [66 45 67 23]]


In [23]:
#column will be deleted at 1th index
arr=np.delete(arr,1,axis=1)
print(arr)

[[11 11 22]
 [22 23 23]
 [43 54 21]
 [66 67 23]]


In [24]:
#row will be deleted at 0 th index
arr=np.delete(arr,0,axis=0)
print(arr)

[[22 23 23]
 [43 54 21]
 [66 67 23]]


In [25]:
#adding row to the 0th index
arr=np.insert(arr,0,[22,22,22],axis=0)
print(arr)

[[22 22 22]
 [22 23 23]
 [43 54 21]
 [66 67 23]]


In [30]:
#adding column to the -1 position
arr=np.insert(arr,-1,[[12,22,33,44]],axis=1)
print(arr)

[[22 22 12 12 12 12 12 12 12 12 12 22]
 [22 23 12 12 12 12 12 12 12 12 22 23]
 [43 54 12 12 12 12 12 12 12 12 33 21]
 [66 67 12 12 12 12 12 12 12 12 44 23]]


In [41]:
#deletig the column 3 to -3
arr=np.delete(arr,[3,4],axis=1)
print(arr)

[[22 22 12 12 12 12 12 22]
 [22 23 12 12 12 12 12 23]
 [43 54 12 12 12 12 12 21]
 [66 67 12 12 12 12 12 23]]
