In [4]:
import numpy as np
arr1=np.array([1,2,3])
arr2=np.array([2,4,6])
print(arr1)
print(arr2)
print("----------------------")
#adding the elements 
result=np.add(arr1,arr2) #1+1,2+4, 3+6
print("Addition of Array",result) 

[1 2 3]
[2 4 6]
----------------------
Addition of Array [3 6 9]


In [8]:
#using the Sum
arr1=np.array([1,2,3])
arr2=np.array([2,4,6])
print(arr1)
print(arr2)
print("----------------------")
#adding the elements 
result=np.sum([arr1,arr2]) 
print("Addition of Array",result) 

[1 2 3]
[2 4 6]
----------------------
Addition of Array 18


In [10]:
#adding the element ussing axix 1 sum
result=np.sum([arr1,arr2],axis=1)
print(result)

[ 6 12]


In [13]:
arr=np.array([1,2,3,4])
print("original array",arr)
result=np.cumsum(arr)
print("Cumutative sum",result)

original array [1 2 3 4]
Cumutative sum [ 1  3  6 10]


In [14]:
arr=np.array([3,2,1,3,5])
print("original array",arr)
result=np.cumsum(arr)
print("Cumutative sum",result)

original array [3 2 1 3 5]
Cumutative sum [ 3  5  6  9 14]


In [15]:
import numpy as np
arr = np.array([1, 2, 3, 4])
x = np.prod(arr)
print(x) #  Returns: 24 because 1*2*3*4 = 24

24


In [16]:
arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([5, 6, 7, 8])
x = np.prod([arr1, arr2])
print(x) # Returns: 40320 because 1*2*3*4*5*6*7*8 = 40320

40320


In [17]:
arr = np.array([[1,2,3],[3,4,5]])
x = np.prod(arr,axis=0) # Here axis=0 Represents Column Product
print(x)

[ 3  8 15]


In [18]:
arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([5, 6, 7, 8])
newarr = np.prod([arr1, arr2], axis=1) # Here axis=1 Represents Row Product
print(newarr)# Returns: [24   1680]

[  24 1680]


In [19]:
arr1=np.array([1,2,4,5])
arr2=np.array([9,5,3,2])
prdarr=np.prod([arr1,arr2],axis=0)
print(prdarr)

[ 9 10 12 10]


In [20]:
arr=np.array([1,2,3,4])
newarr=np.cumprod(arr)
print(newarr)

[ 1  2  6 24]


In [21]:
arr = np.array([[1,2,3],[3,4,5],[2,3,5]])
print("Content of arr")
print(arr)
print("-------------------------")
x = np.cumprod(arr,axis=1) # Here axis=1 Represents Cumulative Row Product 
print(x)

Content of arr
[[1 2 3]
 [3 4 5]
 [2 3 5]]
-------------------------
[[ 1  2  6]
 [ 3 12 60]
 [ 2  6 30]]


In [ ]:
arr = np.array([[1,2,3],[3,4,5],[2,3,5]])
print("Content of arr")
print(arr)
print("-------------------------")
x = np.cumprod(arr,axis=0) # Here axis=0 Represents Cumulative Column Product
print(x)

In [23]:
arr=np.array([3,2,1,3,5])
print("original array",arr)
result=np.sort(arr)
print("sorted Array",result)

original array [3 2 1 3 5]
sorted Array [1 2 3 3 5]


In [30]:
arr=np.array([[3,2,1],[4,3,5]])
print(arr)
newarr=np.sort(arr)
print(newarr)

[[3 2 1]
 [4 3 5]]
[[1 2 3]
 [3 4 5]]


In [31]:
arr=np.array([[3,2,1],[4,3,5]])
print(arr)
newarr=np.sort(arr,axis=0) #col wise
print(newarr)

[[3 2 1]
 [4 3 5]]
[[3 2 1]
 [4 3 5]]


In [32]:
arr=np.array([[3,2,1],[4,3,5]])
print(arr)
newarr=np.sort(arr,axis=1) #row wise
print(newarr)

[[3 2 1]
 [4 3 5]]
[[1 2 3]
 [3 4 5]]


In [33]:
arr = np.array(['banana', 'cherry', 'apple'])
print(np.sort(arr)) # ['apple' 'banana' 'cherry']

['apple' 'banana' 'cherry']
