In [1]:
import numpy as np

In [2]:
#create 2 array for this 
a=np.array([1,2,3,4]).reshape(2,2)
b=np.array([10,20,30,40]).reshape(2,2)
print("----------------------------")
print("Matrix 1")
print(a)
print("----------------------------")
print("Matrix 2")
print(b)
print("-----------------------------")

----------------------------
Matrix 1
[[1 2]
 [3 4]]
----------------------------
Matrix 2
[[10 20]
 [30 40]]
-----------------------------


In [3]:
#matrix operation to be performed
#by using elementwise matrix operation
c=np.add(a,b)
print(c)

[[11 22]
 [33 44]]


In [4]:
c=np.add(b,a)
print(c)

[[11 22]
 [33 44]]


In [5]:
#by using arithimetic operator = +
c=a+b
print(c)

[[11 22]
 [33 44]]


In [6]:
c=b+a
print(c)

[[11 22]
 [33 44]]


In [7]:
#matrix operation to be performed
#by using elementwise matrix operation
c=np.subtract(a,b)
print(c)

[[ -9 -18]
 [-27 -36]]


In [8]:
c=a-b
print(c)

[[ -9 -18]
 [-27 -36]]


In [9]:
c=b-a
print(c)

[[ 9 18]
 [27 36]]


In [10]:
#matrix operation to be performed
#by using elementwise matrix operation
c=np.multiply(a,b)
print(c)

[[ 10  40]
 [ 90 160]]


In [11]:
c=a*b
print(c)

[[ 10  40]
 [ 90 160]]


In [12]:
c=b*a
print(c)

[[ 10  40]
 [ 90 160]]


In [13]:
#matrix operation to be performed
#by using elementwise matrix operation
c=np.dot(a,b)
print(c)

[[ 70 100]
 [150 220]]


In [16]:
#matrix operation to be performed
#by using elementwise matrix operation
c=np.matmul(a,b)
print(c)

[[ 70 100]
 [150 220]]


In [17]:
#matrix operation to be performed
#by using elementwise matrix operation
c=np.divide(a,b)
print(c)

[[0.1 0.1]
 [0.1 0.1]]


In [18]:
c=np.divide(b,a)
print(c)

[[10. 10.]
 [10. 10.]]


In [19]:
c=a/b
print(c)

[[0.1 0.1]
 [0.1 0.1]]


In [20]:
c=b/a
print(c)

[[10. 10.]
 [10. 10.]]


In [21]:
#matrix operation to be performed
#by using elementwise matrix operation
c=np.floor_divide(a,b)
print(c)

[[0 0]
 [0 0]]


In [22]:
c=np.floor_divide(b,a)
print(c)

[[10 10]
 [10 10]]


In [23]:
c=a//b
print(c)

[[0 0]
 [0 0]]


In [24]:
c=b//a
print(c)

[[10 10]
 [10 10]]


In [25]:
#matrix operation to be performed
#by using elementwise matrix operation
c=np.mod(a,b)
print(c)

[[1 2]
 [3 4]]


In [26]:
c=np.mod(b,a)
print(c)

[[0 0]
 [0 0]]


In [27]:
c=a%b
print(c)

[[1 2]
 [3 4]]


In [28]:
c=b%a
print(c)

[[0 0]
 [0 0]]


In [29]:
#matrix operation to be performed
#by using elementwise matrix operation
c=np.power(a,b)
print(c)

[[              1         1048576]
 [205891132094649               0]]


In [30]:
c=np.power(b,a)
print(c)

[[     10     400]
 [  27000 2560000]]


In [31]:
c=a**b
print(c)

[[              1         1048576]
 [205891132094649               0]]


In [32]:
c=b**a
print(c)

[[     10     400]
 [  27000 2560000]]
