In [1]:
import numpy as np
arr1=np.array([1,2,3,4])
arr2=np.array([5,6,7,8])
print(arr1)
print(arr2)

[1 2 3 4]
[5 6 7 8]


In [ ]:
#Performing the Linear Algebra on Arrays
# 1 Dot()
# 2. Inner()
# 3. Outer()
# 4. det()
# 5. solve()
# 6. inv()
# 7. trace()

In [2]:
#dot()
#claculate product of two arrays
result=np.dot(arr1,arr2)
print("Dot Product = ",result)

#Explain = 1*2 + 3*4 + 5*6 = 44

Dot Product =  70


In [9]:
#innerr
arr3=np.array([1,2,3,4])
arr4=np.array([5,6,7,8])
result=np.inner(arr3,arr4)
print("Sum of The Products=",result)

Sum of The Products= 70


In [10]:
#example of inner() with 2d array 
array1 = np.array([[1, 3], 
                   [5, 7]])
array2 = np.array([[2, 4], 
                   [6, 8]])
result=np.inner(array1,array2)
print(result)

#1*2+3*4        1*6+3*8
#5*2+7*4        5*6+7*8

[[14 30]
 [38 86]]


In [13]:
#outer
arr3=np.array([1,2,3,4])
arr4=np.array([5,6,7,8])
result=np.outer(arr3,arr4)
print("Sum of The Products=")
print(result)

Sum of The Products=
[[ 5  6  7  8]
 [10 12 14 16]
 [15 18 21 24]
 [20 24 28 32]]


In [ ]:
#Explation
#1*2      1*4       1*6        
#3*2      3*4       3*6
#5*2      5*4       5*6

In [14]:
#det
array=np.array([
    [1,2],
    [3,4]
])
result=np.linalg.det(array)
print(result)

-2.0000000000000004


In [16]:
#Solve()
a=np.array([[2, 4], 
           [6, 8]])
b=np.array([5,6])
x=np.linalg.solve(a,b)
print(x)

[-2.    2.25]


In [17]:
#Inv()
array1=np.array([[2,4],[6,8]])
#compute the inverse of the matrix
result=np.linalg.inv(array1)
print(result)

[[-1.    0.5 ]
 [ 0.75 -0.25]]


In [19]:
#trace()
#define a 3*3 matrix
array1=np.array([[6,3,2],[2,3,4],[6,4,3]])
#compute the trace of the matrix
result=np.trace(array1)
print(result)

#In The the diagonal elements will be calculated sum 
#6+3+3 = 12 

12
