In [1]:
import numpy as np
arr=np.arange(6)
print(arr)
#spliting the array into 2 with split()
narr=np.split(arr,2)
print(narr)

[0 1 2 3 4 5]
[array([0, 1, 2]), array([3, 4, 5])]


In [7]:
#spliting the unequal array unsing array.split()
arr=np.arange(7)
print(arr)
#spliting the array into 2 col
narr=np.array_split(arr,2)
print(narr)

[0 1 2 3 4 5 6]
[array([0, 1, 2, 3]), array([4, 5, 6])]


In [8]:
arr=np.arange(13)
print(arr)
#spliting the array into 2 col
narr=np.array_split(arr,3)
print(narr)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12]
[array([0, 1, 2, 3, 4]), array([5, 6, 7, 8]), array([ 9, 10, 11, 12])]


In [11]:
#spliting the numpy 2d array
array = np.array([[3, 2, 1], [8, 9, 7], [4, 6, 5]])
narr=np.split(array,3,axis=1) #col wise
print(narr)

[array([[3],
       [8],
       [4]]), array([[2],
       [9],
       [6]]), array([[1],
       [7],
       [5]])]


In [12]:
#spliting the numpy 2d array
array = np.array([[3, 2, 1], [8, 9, 7], [4, 6, 5]])
narr=np.split(array,3,axis=0) #row wise
print(narr)

[array([[3, 2, 1]]), array([[8, 9, 7]]), array([[4, 6, 5]])]


In [13]:
# Creating an example matrix
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])

# Vertical splitting into 2 subarrays along axis=0
result = np.vsplit(matrix, 2)  # OR   result=np.split(matrix,2,axis=0)
print("Matrix:")
print(matrix)
print("\nResult after numpy.vsplit():")
print(result)


Matrix:
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

Result after numpy.vsplit():
[array([[1, 2, 3],
       [4, 5, 6]]), array([[ 7,  8,  9],
       [10, 11, 12]])]


In [17]:
# Creating an example matrix
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])

# Vertical splitting into 2 subarrays along axis=0
result = np.hsplit(matrix,3)  # OR   result=np.split(matrix,2,axis=1)
print("Matrix:")
print(matrix)
print("\nResult after numpy.hsplit():")
print(result)

Matrix:
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

Result after numpy.hsplit():
[array([[ 1],
       [ 4],
       [ 7],
       [10]]), array([[ 2],
       [ 5],
       [ 8],
       [11]]), array([[ 3],
       [ 6],
       [ 9],
       [12]])]


In [20]:
arr = np.arange(24).reshape(2, 3, 4)
result = np.dsplit(arr, 2)

print("Original 3D Array:")
print(arr)
print("\nResult after numpy.dsplit():")
print(result)


Original 3D Array:
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]

Result after numpy.dsplit():
[array([[[ 0,  1],
        [ 4,  5],
        [ 8,  9]],

       [[12, 13],
        [16, 17],
        [20, 21]]]), array([[[ 2,  3],
        [ 6,  7],
        [10, 11]],

       [[14, 15],
        [18, 19],
        [22, 23]]])]
