In [ ]:
#Syntax = import numpy as np
#        np.random.functionname()
#Syntax 2 = from numpy import random
#           random.functionname()
#syntax 3= from numpy import random as r
#           r.functionname()

In [1]:
#1.randint()

#syntax 1 = numpy.random.randint(value)

import numpy as np
from numpy import random as r
a=r.randint(12)
print(a)

6


In [2]:
#syntax 2 = numpy.random.randint(low , high)
import numpy as np
from numpy import random as r
a=r.randint(1,15)
print(a)

13


In [3]:
#syntax 3 = numpy.random.randint(low , high,size)
import numpy as np
from numpy import random as r
a=r.randint(1,15,size=4)
print(a)

[14  8  5 13]


In [4]:
b=r.randint(12,size=5)
print(b)

[ 9  4 11 11  5]


In [ ]:
#rand - values between 0.0 to 1.0

#S1= numpy.random.rand()
#s2= numpy.random.rand(value)
#s3= numpy.random.rand(rows,cols)

In [5]:
a=r.rand(3)
print(a)

[0.29761523 0.09870433 0.15897923]


In [6]:
b=r.rand(4)
print(b)

[0.49210024 0.45985186 0.6169403  0.53415839]


In [7]:
a=r.rand(3,4)
print(a)

[[0.00340173 0.54144676 0.31900246 0.94068082]
 [0.2597704  0.22607892 0.73642775 0.54465078]
 [0.93688983 0.88609763 0.37544417 0.55752177]]


In [8]:
b=r.rand(2,2)
print(b)

[[0.62914184 0.6163288 ]
 [0.74427662 0.1262351 ]]


In [9]:
#uniform

#s1= numpy.random.uniform()
#s2=numpy.random.uniform(low,high)
#s3=numpy.random.uniform(low,high,size)

a=r.uniform()
print(a)

0.9264887045430975


In [10]:
a=r.uniform(1,3)
print(a)

2.477225336334583


In [11]:
a=r.uniform(1,4,3)
print(a)

[2.54485619 1.89124692 2.36585992]


In [12]:
b=r.uniform(3,4)
print(b)

3.776193482534833


In [ ]:
#randn()

#s1= numpy.random.randn()
#s2= numpy.random.randn(values)
#s3= numpy.random.randn(rows,cols)
#s4= numpy.random.randn(no of matrices, rows, cols)

In [13]:
a=r.randn()
print(a)

0.8093767674342113


In [14]:
a=r.randn(3)
print(a)

[ 1.09622402 -1.35134179 -0.80205962]


In [15]:
a=r.randn(3,6)
print(a)

[[-0.91754679  0.34080389  0.5560627   1.35868631 -0.3718197  -0.17559795]
 [-0.4652348   3.0415906   0.02604884  0.7328242  -0.6395921  -0.46743174]
 [-1.19716169 -0.37855881  0.03800492  0.44456514 -0.56661985 -0.39318771]]


In [16]:
a=r.randn(2,4,4)
print(a)

[[[-0.70512533  0.51345578 -1.92382237 -0.06875349]
  [ 0.3409791  -0.27603995  0.59967675  1.38115085]
  [ 1.19483632 -0.50673492  0.11032411 -0.13990046]
  [ 0.34957537  0.08020777 -2.06441139 -1.93410424]]

 [[-0.2613616   1.39824609  0.3956103   0.19870686]
  [-0.8468167   0.52130686 -0.25266771 -1.02742253]
  [-0.82259101  0.76471474 -1.3372226   0.34551998]
  [ 0.62560827 -0.12893044 -2.17101767  0.87437763]]]


In [17]:
a=r.randn(5)
print(a)

[-0.7489536   0.50235856  0.99570433  1.59661692 -1.51104267]


In [18]:
#normaml

import numpy as np
from numpy import random as r

rv=r.normal()
print(rv)

-0.5769602053030803


In [19]:
rv=r.normal(2)
print(rv)

2.7318683117579163


In [20]:
rv=r.normal(2,4)
print(rv)

0.24381866518149797


In [21]:
rv=r.normal(2,4,size=4)
print(rv)

[ 3.65887678 -1.81300388 -4.79038017  0.32902056]


In [22]:
#choice

a=np.array([10,20,30,40,50,60])
print(a)
cv=r.choice(a)
print(cv)

[10 20 30 40 50 60]
30


In [23]:
cv=r.choice(a)
print(cv)

60


In [26]:
a=r.randint(1,100,size=20)
print(a)
b=r.choice(a)
print(b)

[41 96 87 96 11  4 51 75 32  1 12 37 76 38 18 16 59 35 90 68]
18


In [28]:
b=r.choice(a,size=(2,2))
print(b)

[[16 96]
 [37  4]]


In [35]:
#shuffle()

#syntax = varname=numpy.random.shuffle(x)

a=r.randint(1,50,size=5)
print(a)
a=r.shuffle(a)
print(a)

[23  8 40 47 31]
None


In [36]:
a=np.arange(48).reshape(4,3,4)
np.random.shuffle(a)
print(a)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[36 37 38 39]
  [40 41 42 43]
  [44 45 46 47]]

 [[24 25 26 27]
  [28 29 30 31]
  [32 33 34 35]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
