In [5]:
import numpy as np
a=np.array([10,20,30,40,50,60,70,80,90,15,25,35])
print("-------------------------------------------------")
print("Content of a")
print(a)
print("Dimension of a=",a.ndim)
print("Shape of a=",a.shape)
print("Size of a=",a.size)
print("-------------------------------------------------")

-------------------------------------------------
Content of a
[10 20 30 40 50 60 70 80 90 15 25 35]
Dimension of a= 1
Shape of a= (12,)
Size of a= 12
-------------------------------------------------


In [6]:
#basic slicing in numpy [start:stop:step]
a[0:3]

array([10, 20, 30])

In [7]:
a[0:5]

array([10, 20, 30, 40, 50])

In [9]:
a[-4:-1]

array([90, 15, 25])

In [10]:
a[0:]

array([10, 20, 30, 40, 50, 60, 70, 80, 90, 15, 25, 35])

In [11]:
a[3::]

array([40, 50, 60, 70, 80, 90, 15, 25, 35])

In [12]:
a[1::3]

array([20, 50, 80, 25])

In [13]:
a[2::2]

array([30, 50, 70, 90, 25])

In [14]:
a[::-1]

array([35, 25, 15, 90, 80, 70, 60, 50, 40, 30, 20, 10])

In [15]:
a[0::]

array([10, 20, 30, 40, 50, 60, 70, 80, 90, 15, 25, 35])

In [ ]:
#Basic Slicing on 2-D 
#Syntax-1:   1DNdaaray[RowStart:RowStop:RowStep]
#Syntax-2:   1DNdaaray[RowStart:RowStop:RowStep,ColStrt:ColStop:ColStep]

In [16]:
import numpy as np
a=np.array([10,20,30,40,50,60,70,80,90,15,25,35]).reshape(3,4)
print("-------------------------------------------------")
print("Content of a")
print(a)
print("Dimension of a=",a.ndim)
print("Shape of a=",a.shape)
print("Size of a=",a.size)
print("-------------------------------------------------")

-------------------------------------------------
Content of a
[[10 20 30 40]
 [50 60 70 80]
 [90 15 25 35]]
Dimension of a= 2
Shape of a= (3, 4)
Size of a= 12
-------------------------------------------------


In [17]:
a[0,1]

np.int64(20)

In [18]:
a[1::2]

array([[50, 60, 70, 80]])

In [19]:
a[0:2]

array([[10, 20, 30, 40],
       [50, 60, 70, 80]])

In [20]:
a[0:1:2,0:1:1]

array([[10]])

In [21]:
a[1:2,1:2]

array([[60]])

In [22]:
a[0:2,2:3]

array([[30],
       [70]])

In [25]:
a[1:1][1:3]

array([], shape=(0, 4), dtype=int64)

In [26]:
a[0::,0:1]

array([[10],
       [50],
       [90]])

In [27]:
a[0:4,:1]

array([[10],
       [50],
       [90]])

In [29]:
a[:4,:1]

array([[10],
       [50],
       [90]])

In [32]:
a[0:1,:1:1]

array([[10]])

In [34]:
a[0:4,3:]

array([[40],
       [80],
       [35]])

In [36]:
a[0:4,-1:]

array([[40],
       [80],
       [35]])