In [7]:
#Statistical Operation
import numpy as np
from numpy import random
a=np.array([10,20,30,40,50])
print(a)

[10 20 30 40 50]


In [2]:
a=np.max(a)
print(a)

50


In [4]:
np.max(a)

np.int64(50)

In [14]:
a=np.random.randint(10,30,size=15)
print("content of a")
print(a)

content of a
[10 26 18 15 26 23 16 11 27 16 25 10 12 17 26]


In [15]:
#find the max and min value fromm 1 dim
maxv=np.amax(a)
minv=np.amin(a)
print("max value =",maxv)
print("min value=",minv)

max value = 27
min value= 10


In [16]:
#find max and min value from 2d dim
a=np.random.randint(10,30,size=(4,4))
print(a)
maxv=np.amax(a)
minv=np.amin(a)
print("max value =",maxv)
print("min value=",minv)

[[27 24 13 26]
 [29 19 14 15]
 [27 15 22 22]
 [11 14 20 21]]
max value = 29
min value= 11


In [17]:
#Now My Req: To find Column-wise and Row-wise Max and Min Values
#To Do the above, we must use axis concept.
# if axis=0 then It refers COLUMNS
# if axis=1 then It refers ROWS
maxv=np.amax(a)
minv=np.amin(a)
colmax=np.amax(a,axis=0)
rowmax=np.amax(a,axis=1)
colmin=np.amin(a,axis=0)
rowmin=np.amin(a,axis=1)
print("--------------------------------------")
print("Given Matrix")
print(a)
print("--------------------------------------")
print("Max Value=",maxv)
print("Min Value=",minv)
print("--------------------------------------")
print("Column Max=",colmax)
print("Row Max=",rowmax)
print("Column Min=",colmin)
print("Row Min=",rowmin)
print("--------------------------------------")

--------------------------------------
Given Matrix
[[27 24 13 26]
 [29 19 14 15]
 [27 15 22 22]
 [11 14 20 21]]
--------------------------------------
Max Value= 29
Min Value= 11
--------------------------------------
Column Max= [29 24 22 26]
Row Max= [27 29 27 21]
Column Min= [11 14 13 15]
Row Min= [13 14 15 11]
--------------------------------------


In [18]:
#Find the mean on ndarray by using mean()--1-Dim
a=np.array([3,1,2,4])
m=np.mean(a)
print("Mean({})={}".format(a,m))

Mean([3 1 2 4])=2.5


In [19]:
#Our Own Code for Finding Sum and Mean (Average)
s=0
for v in a:
    s=s+v
print("Sum=",s)
print("mean({})={}".format(a,s/len(a)))

Sum= 10
mean([3 1 2 4])=2.5


In [20]:
#Find the mean on ndarray by using mean()--2-Dim
#Find the mean for Col and Row
a=np.array([3,1,2,4]).reshape(2,2)
print("-------------------------------------")
print("Matrix-A")
print(a)
print("-------------------------------------")
m=np.mean(a)
cm=np.mean(a,axis=0)
rm=np.mean(a,axis=1)
print("Mean\n({})={}".format(a,m))
print("Col Mean\n({})={}".format(a,cm))
print("Row Mean\n({})={}".format(a,rm))
print("-------------------------------------")

-------------------------------------
Matrix-A
[[3 1]
 [2 4]]
-------------------------------------
Mean
([[3 1]
 [2 4]])=2.5
Col Mean
([[3 1]
 [2 4]])=[2.5 2.5]
Row Mean
([[3 1]
 [2 4]])=[2. 3.]
-------------------------------------


In [21]:
#Find the mean on ndarray by using mean()--2-Dim
#Find the mean for Col and Row
a=np.random.randint(1,50,size=(5,5))
print("-------------------------------------")
print("Matrix-A")
print(a)
print("-------------------------------------")
m=np.mean(a)
cm=np.mean(a,axis=0)
rm=np.mean(a,axis=1)
print("Mean\n({})={}".format(a,m))
print("Col Mean\n({})={}".format(a,cm))
print("Row Mean\n({})={}".format(a,rm))
print("-------------------------------------")

-------------------------------------
Matrix-A
[[38 17 30 31 37]
 [ 3 16 12 20 11]
 [33 11  2 24 29]
 [35 16 32  6 30]
 [ 8 47 29 40 37]]
-------------------------------------
Mean
([[38 17 30 31 37]
 [ 3 16 12 20 11]
 [33 11  2 24 29]
 [35 16 32  6 30]
 [ 8 47 29 40 37]])=23.76
Col Mean
([[38 17 30 31 37]
 [ 3 16 12 20 11]
 [33 11  2 24 29]
 [35 16 32  6 30]
 [ 8 47 29 40 37]])=[23.4 21.4 21.  24.2 28.8]
Row Mean
([[38 17 30 31 37]
 [ 3 16 12 20 11]
 [33 11  2 24 29]
 [35 16 32  6 30]
 [ 8 47 29 40 37]])=[30.6 12.4 19.8 23.8 32.2]
-------------------------------------


In [22]:
#Find the median of ndarray--1-Dim with ODD Number of Elements
a=np.array([10,2,14,3,18,20,5])
print("----------------------------------")
print("Content of a")
print(a)
print("----------------------------------")
m=np.median(a)
print("Median({})={}".format(a,m))
print("----------------------------------")

----------------------------------
Content of a
[10  2 14  3 18 20  5]
----------------------------------
Median([10  2 14  3 18 20  5])=10.0
----------------------------------


In [23]:
#Find the median of ndarray--1-Dim with Even Number of Elements
a=np.array([10,2,14,3,18,20,5,6])
print("----------------------------------")
print("Content of a")
print(a)
print("----------------------------------")
m=np.median(a)
print("Median({})={}".format(a,m))
print("----------------------------------")

----------------------------------
Content of a
[10  2 14  3 18 20  5  6]
----------------------------------
Median([10  2 14  3 18 20  5  6])=8.0
----------------------------------


In [24]:
#Find the median of ndarray--1-Dim with Even Number of Elements
a=np.array([10,2,14,3,18,20,5,6,12,22,13,25,19,4,1,9]).reshape(4,4)
print("----------------------------------")
print("Content of a")
print(a)
print("----------------------------------")
m=np.median(a)
print("Median\n({})={}".format(a,m))
print("----------------------------------")
#My Req : To get col-wise and Row-wise  Median
cm=np.median(a,axis=0)
rm=np.median(a,axis=1)
print("Col Median\n({})={}".format(a,cm))
print("Row Median\n({})={}".format(a,rm))

----------------------------------
Content of a
[[10  2 14  3]
 [18 20  5  6]
 [12 22 13 25]
 [19  4  1  9]]
----------------------------------
Median
([[10  2 14  3]
 [18 20  5  6]
 [12 22 13 25]
 [19  4  1  9]])=11.0
----------------------------------
Col Median
([[10  2 14  3]
 [18 20  5  6]
 [12 22 13 25]
 [19  4  1  9]])=[15.  12.   9.   7.5]
Row Median
([[10  2 14  3]
 [18 20  5  6]
 [12 22 13 25]
 [19  4  1  9]])=[ 6.5 12.  17.5  6.5]


In [25]:
#Finding Variance by using var()
a=np.array([3,1,2,4])
print("Content of a")
print(a)
v=np.var(a)
print("Variance=",v)

Content of a
[3 1 2 4]
Variance= 1.25


In [26]:
#Find Col and Row-wise variance
a=np.array([3,1,2,4]).reshape(2,2)
print("------------------------------------")
print("Content of a")
print(a)
print("------------------------------------")
v=np.var(a)
print("Variance=",v)
cv=np.var(a,axis=0)
rv=np.var(a,axis=1)
print("Col Var=",cv)
print("Row Var=",rv)
print("------------------------------------")

------------------------------------
Content of a
[[3 1]
 [2 4]]
------------------------------------
Variance= 1.25
Col Var= [0.25 2.25]
Row Var= [1. 1.]
------------------------------------


In [27]:
#Find Col and Row-wise variance
a=np.arange(4*3).reshape(4,3)
print("------------------------------------")
print("Content of a")
print(a)
print("------------------------------------")
v=np.var(a)
print("Variance=%0.2f" %v)
cv=np.var(a,axis=0)
rv=np.var(a,axis=1)
print("Col-wise Var")
for v in cv:
    print(round(v,2),end="  ")
print()    
print("Row-wise Var")
for v in rv:
    print(round(v,2),end="  ")
print()    
print("------------------------------------")

------------------------------------
Content of a
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
------------------------------------
Variance=11.92
Col-wise Var
11.25  11.25  11.25  
Row-wise Var
0.67  0.67  0.67  0.67  
------------------------------------


In [28]:
#We Know that standard Deviation= sqrt(Var)
#Find Col and Row-wise variance
a=np.array([3,1,2,4]).reshape(2,2)
print("------------------------------------")
print("Content of a")
print(a)
print("------------------------------------")
s=np.std(a)
print("Standard Deviation=",s)
csd=np.std(a,axis=0)
rsd=np.std(a,axis=1)
print("Col Std =",csd)
print("Row Std=",rsd)
print("------------------------------------")

------------------------------------
Content of a
[[3 1]
 [2 4]]
------------------------------------
Standard Deviation= 1.118033988749895
Col Std = [0.5 1.5]
Row Std= [1. 1.]
------------------------------------


In [29]:
# Find the Mode of ndarray 
a=np.array([3,1,2,4,3,3])
print("------------------------------------")
print("Content of a")
print(a)
print("------------------------------------")
#m=np.mode(a)-----------AttributeError: module 'numpy' has no attribute 'mode'

------------------------------------
Content of a
[3 1 2 4 3 3]
------------------------------------


In [30]:
# Find the Mode of ndarray by using a pre-defined Module statistics of python
import statistics as s
a=np.array([3,1,2,4,3,3])
print("------------------------------------")
print("Content of a")
print(a)
print("------------------------------------")
m=s.mode(a)
print("Mode=",m)

------------------------------------
Content of a
[3 1 2 4 3 3]
------------------------------------
Mode= 3


In [31]:
# Find the Mode of ndarray by using a pre-defined Module statistics of python
import statistics as s
a=np.array([3,1,2,4,3,3,1,1])
print("------------------------------------")
print("Content of a")
print(a)
print("------------------------------------")
m=s.mode(a)
print("Mode=",m)

------------------------------------
Content of a
[3 1 2 4 3 3 1 1]
------------------------------------
Mode= 3


In [32]:
# Find the Mode of ndarray by using a pre-defined Module statistics of python
import statistics as s
a=np.array([1,3,2,4,3,3,1,1,2,2,3])
print("------------------------------------")
print("Content of a")
print(a)
print("------------------------------------")
m=s.multimode(a)
print("Mode=",m)

------------------------------------
Content of a
[1 3 2 4 3 3 1 1 2 2 3]
------------------------------------
Mode= [np.int64(3)]
