In [2]:
import numpy as np
from numpy import random
a=np.linspace(2,10,2)
print(a)

[ 2. 10.]


In [10]:
a=np.linspace(2,4)
print(a)

[2.         2.04081633 2.08163265 2.12244898 2.16326531 2.20408163
 2.24489796 2.28571429 2.32653061 2.36734694 2.40816327 2.44897959
 2.48979592 2.53061224 2.57142857 2.6122449  2.65306122 2.69387755
 2.73469388 2.7755102  2.81632653 2.85714286 2.89795918 2.93877551
 2.97959184 3.02040816 3.06122449 3.10204082 3.14285714 3.18367347
 3.2244898  3.26530612 3.30612245 3.34693878 3.3877551  3.42857143
 3.46938776 3.51020408 3.55102041 3.59183673 3.63265306 3.67346939
 3.71428571 3.75510204 3.79591837 3.83673469 3.87755102 3.91836735
 3.95918367 4.        ]


In [12]:
a=np.linspace(4,8)
print(a)


[4.         4.08163265 4.16326531 4.24489796 4.32653061 4.40816327
 4.48979592 4.57142857 4.65306122 4.73469388 4.81632653 4.89795918
 4.97959184 5.06122449 5.14285714 5.2244898  5.30612245 5.3877551
 5.46938776 5.55102041 5.63265306 5.71428571 5.79591837 5.87755102
 5.95918367 6.04081633 6.12244898 6.20408163 6.28571429 6.36734694
 6.44897959 6.53061224 6.6122449  6.69387755 6.7755102  6.85714286
 6.93877551 7.02040816 7.10204082 7.18367347 7.26530612 7.34693878
 7.42857143 7.51020408 7.59183673 7.67346939 7.75510204 7.83673469
 7.91836735 8.        ]


In [16]:
a=np.identity(5)
print(a)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [17]:
b=np.identity(3,dtype=int)
print(b)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [18]:
c=np.identity(4,dtype=int)
print(c)

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]


In [19]:
a=np.eye(3)
print(a)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [20]:
a=np.eye(3,2)
print(a)

[[1. 0.]
 [0. 1.]
 [0. 0.]]


In [21]:
a=np.eye(4,3)
print(a)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 0.]]


In [23]:
a=np.eye(3,2,k=0)
print(a)

[[1. 0.]
 [0. 1.]
 [0. 0.]]


In [35]:
a=np.array([10,20,30,40])
print(a)
b=np.array([1,2,3,4])
print(b)

[10 20 30 40]
[1 2 3 4]


In [36]:
c=np.hstack((a,b))
print(c)

[10 20 30 40  1  2  3  4]


In [37]:
b=np.hstack((a,b))
print(a)

[10 20 30 40]


In [4]:
c=np.array([10,20,30,40]).reshape(2,2)
print(c)
d=np.array([1,2,3,4]).reshape(2,2)
print(d)

[[10 20]
 [30 40]]
[[1 2]
 [3 4]]


In [7]:
e=np.vstack((c,d))
print("The VStack Array")
print(e)
print("Hatack Stack Array")
f=np.hstack((c,d))
print(f)

The VStack Array
[[10 20]
 [30 40]
 [ 1  2]
 [ 3  4]]
Hatack Stack Array
[[10 20  1  2]
 [30 40  3  4]]


In [11]:
#Random Module
import numpy as np
from numpy import random as r
a=r.randint(0,15,size=12)
print(a)

[ 9  3 10  5  2  2  8 12  6  0 10  3]


In [18]:
b=r.randint(0,12,size=12).reshape(3,4)
print(b)

[[ 7 10  7  8]
 [ 2  5  7 11]
 [ 1  9  3  3]]


In [19]:
b=r.rand(23) #between 0.0 to 0.1
print(b)

[0.00882159 0.84804968 0.76271707 0.47334439 0.55543479 0.92330763
 0.94669195 0.65660731 0.50029692 0.89611584 0.0206476  0.58570276
 0.18962563 0.93509658 0.0078471  0.11080467 0.75869632 0.82795032
 0.67167913 0.3735713  0.61069487 0.86739079 0.71077156]


In [20]:
c=r.rand(4)
print(c)

[0.42099916 0.98316044 0.94513107 0.19918974]


In [22]:
a=r.uniform(3,2)
print(a)

2.8450598831299088


In [23]:
a=r.randn(22)
print(a)

[-1.36457376 -1.13376345 -0.17811866  0.17680097  0.78386152 -0.65245081
  0.3216996   0.20934368  0.00564992  1.87629777  0.333707   -0.18544964
 -0.73476902  0.63117862 -0.44544668  0.74835399  0.82617135 -1.52083465
 -0.90611678  0.91139628  0.29745777  0.94588869]


In [24]:
a=r.randn(2,4)
print(a)

[[ 0.48082481 -0.36407559 -0.31565735  0.19900972]
 [-0.98421029 -2.12780469  0.15897099 -0.95463116]]


In [25]:
a=r.randn(2,4,2)
print(a)

[[[-1.18545604 -0.32471267]
  [-0.77518469  0.68862277]
  [-0.23591215  0.07935747]
  [-0.27261431 -0.27716144]]

 [[-0.92966652  0.65192319]
  [ 1.46918692 -1.60826068]
  [ 0.58051722  1.54929956]
  [-0.52420551  1.82165461]]]


In [26]:
a=r.normal(3)
print(a)

3.689503375639588


In [27]:
a=r.normal(3,2)
print(a)

3.256789662607254


In [28]:
a=r.normal(2,3,size=4)
print(a)

[-0.68200405 -4.53622681 -0.42783036  5.54419981]


In [30]:
a=np.array([10,20,30,40,50])
print(a,type(a))
cv=r.choice(a)
print(cv)

[10 20 30 40 50] <class 'numpy.ndarray'>
40


In [31]:
print(r.choice(a))

50


In [32]:
print("Your Choice Number=",r.choice(a))

Your Choice Number= 30


In [33]:
print("Your Choice Number=",r.choice(a))

Your Choice Number= 10
